# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05239c9a9be7503676def3af99b923dd111a899767e87d6b5a305fc58a06de28ab49ad4888cfb0b07d37ccd71ea072bd8a5660b01b2292df6b68c7a661de44ea

test:
  secret_key_base: c1826dad86332425bb2a0da1f61315318a0bdbece7fbcbaeb2c40e015815d743138cf20662aa01e6328912f1747a9bc1c8365d723039a4df3001df7768446120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
